### ISSUE TITLE
Use kubernetes csr to generate an intermediate mitm CA

### ISSUE THREAD

**Issue by hh** [danisla/kubernetes-tproxy-example#1]
I'm attempting to create an intermediary CA by adding 'cert sign' to the usages section of the CSR.

However when I add 'cert sign', I can approve those CSRs get approved, but they are never issued:

```
cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: $CSR_NAME
  spec:
    groups:
    - system:authenticated
    request: $(cat mitm.csr | base64 | tr -d '\n')
    usages:
    - digital signature
    - key encipherment
    - server auth
    - cert sign # adding this line results in CSRs that get approved, but never issued
EOF
```

Is there some line of code on the way to [CFSSL sign](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/signer/cfssl_signer.go#L113) that would allow me to see why the CSR's are not being issued?
